### ISSUE TITLE
Crash when creating new profile if print spooler service is not started

### ISSUE THREAD

**Issue by FMJ999** [netprofilesmod/netprofilesmod#68]
OS : Windows 8.1 Pro (FRA)
No issue when the service is started.
This bug is totally reproductible.

Thank you for your attention and for this vital software !
![screen shot 06-15-16 at 12 21 pm](https://cloud.githubusercontent.com/assets/19949693/16076606/5a8db1de-32f4-11e6-9016-41ed374f4932.PNG)

**Comment by geissbuehler** [comment]
Thanks for reporting this bug. Version 0.2.5 with the fix is now released!
