### ISSUE TITLE
Opened Window impossible to find

### ISSUE THREAD

**Issue by jclavier06** [netprofilesmod/netprofilesmod#73]
There is a while i am using Net Profile Mod (last version), but since a week, impossible to see the opened window. Even if the windows 7 preview show it, I can not find the opened window anywhere.
![image](https://user-images.githubusercontent.com/32450455/31070070-59f5912a-a75f-11e7-97cc-b82d346eefbd.png)

**Comment by geissbuehler** [comment]
This is a duplicate of #29. You can bring the application window back to the visible part of the screen with one of these tricks: https://superuser.com/questions/53585/how-to-move-windows-that-open-up-offscreen
