### ISSUE TITLE
VS2017 : error on compilation

### ISSUE THREAD

**Issue by droumanet** [netprofilesmod/netprofilesmod#77]
I'm beginner with C# but I can't create executable (without changing any files) because, I've these errors : 
- AppModule.Globals.dll not found
- all "VC80_CRT" are not found
- component "MessageBoxHook" not found

Could someone help me ? thanks.

**Comment by geissbuehler** [comment]
Hi droumanet

I'm glad to see that someone tries to improve the project. My permanent lack of time prevents me from contributing.
Did you checkout the branch vs2015? In this branch the project is migrated to a  Visual Studio 2015 solution that should work with VS 2017 as well. Please have a look at the hints Debugging.txt as well.

Best regards
Urs

**Comment by droumanet** [comment]
Hi Urs,
I confirm I'm using the vs2015 branch but still having these errors. I really want to help you on this project.
I'm french (my VS2017 IDE is so in french) but here is one of error line :
Erreur		Impossible de copier le fichier "..\3rd Party\Microsoft\VC80_CRT\bin\AnyCPU\Microsoft.VC80.CRT\Microsoft.VC80.CRT.manifest", car il est introuvable.	Net Profiles mod	E:\david\WorkSpaces\Visual Studio 2015\Net Profiles Mod\Net Profiles mod\Net Profiles mod.vbproj	353	

Best regards,
David

**Comment by geissbuehler** [comment]
..\3rd Party\Microsoft\VC80_CRT\bin\AnyCPU indicates that you are trying to compile for the AnyCPU platform, but according to Debugging.txt this will fail:
Building only succeeds when the x86 platform or the x64 platform is selected. Building the AnyCPU release will fail, it is reserved for future use when MessageBoxHook is no more required.

**Comment by droumanet** [comment]
That's right ! I've changed to x64, then to x86... but still errors about 
E:\david\WorkSpaces\Visual Studio 2015\Net Profiles Mod\AppModule.NamedPipes\bin\Debug\**AppModule.Globals.dll**
E:\david\WorkSpaces\Visual Studio 2015\Net Profiles Mod\AppModule.NamedPipes\bin\Debug\**AppModule.NamedPipes.dll** introuvable

I'm beginner (I feel I'll progress quickly with this project ;) ) and I'm not able to change settings in configuration manager because list let me only <any CPU>, <new...> or <modify...>
![image](https://user-images.githubusercontent.com/24438463/37554458-4e73c2b6-29d9-11e8-882f-60d4ac7ed4b9.png)

Your project is very interesting (opensource, power functions, autoconfiguration from SSID detection...) I really want to improve it :)

**Comment by droumanet** [comment]
Don't care about my previous message : I've unchecked a box with "create a new profile"... now I'm able to compile and debug ! 
I've to study your code and see how to write some enhancements (looking to these issues in github project). **Thanks for your help !**
