### ISSUE TITLE
Thanks for the program!

### ISSUE THREAD

**Issue by mrkaban** [netprofilesmod/netprofilesmod#79]
Thanks for the program under the GNU GPL license !!! Quite high quality and well crafted! And special thanks for translating the interface into Russian. Added a program to the free software site ([link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D1%83%D1%82%D0%B8%D0%BB%D0%B8%D1%82%D1%8B/%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B0/net-profiles-mod.html)).

**Comment by geissbuehler** [comment]
Thank for listing the program on континентсвободы.рф!
